"""
Django settings for gmp project.
Generated by 'django-admin startproject' using Django 3.2.4.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging
import os
from datetime import datetime, timedelta
from logging.handlers import RotatingFileHandler

import environ

logger = logging.getLogger(__name__)


env = environ.Env()

# Build paths inside the project like this: BASE_DIR('dir')
BASE_DIR = environ.Path(__file__) - 2


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# Django Secret Key
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")


# Debug settings
# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env("DJANGO_DEBUG", default=False)


# Allowed hosts

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add third party apps here
THIRD_PARTY_APPS = ["rest_framework", "simple_history"]

# Add new project apps here
LOCAL_APPS = [
    "core.apps.CoreConfig",
    "users.apps.UsersConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

# CSRF_TRUSTED_ORIGINS = [
#     'domena',
# ]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DEBUG:
    DATABASES = {"default": env.db("DATABASE_URL_DEV")}
else:
    DATABASES = {"default": env.db("DATABASE_URL_PROD")}

DATABASES["default"]["CONN_MAX_AGE"] = 600


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"


# Media files (images, videos, pdfs, docs, etc.)

if DEBUG:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR("media")
else:
    pass


# Admin URL path

ADMIN_URL = env("DJANGO_ADMIN_URL", default="admin/")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# User model

AUTH_USER_MODEL = "users.CustomUser"


# SSL for Nginx

SECURE_ORIGIN_SSL_HEADER = {"HTTP_X_FORWARDED_PROTO", "https"}


# CORS Settings

CORS_ORIGIN_ALLOW_ALL = DEBUG

if not CORS_ORIGIN_ALLOW_ALL:
    CORS_ORIGIN_ALLOWLIST = env("CORS_ORIGIN_ALLOWLIST", default=[])


# Rest Framework Settings

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": "rest_framework.permissions.IsAuthenticated",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# JWT Settings

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


# AWS Config

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")

# AWS S3 Config

if "AWS_STORAGE_BUCKET_NAME" in env:
    # TODO: Create AWS S3 Buckets config
    pass


# Logs monitoring service

# TODO: Choose Rollbar or Sentry for logs monitoring

# Logging configuration
LOG_DIR = BASE_DIR("logs")

# Create logs directory if it doesn't exist
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# Na początku pliku
class DailyRotatingFileHandler(RotatingFileHandler):
    def __init__(self, filename_pattern, *args, **kwargs):
        self.filename_pattern = filename_pattern
        filename = self._get_current_filename()
        super().__init__(filename, *args, **kwargs)

    def _get_current_filename(self):
        return self.filename_pattern.format(datetime.now().strftime("%Y-%m-%d"))

    def _open(self):
        self.baseFilename = self._get_current_filename()
        return open(self.baseFilename, self.mode, encoding=self.encoding)


# Configuration of logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file_debug": {
            "level": "DEBUG",
            "class": "config.settings.DailyRotatingFileHandler",
            "filename_pattern": os.path.join(LOG_DIR, "debug_{}.log"),
            "maxBytes": 0,
            "backupCount": 0,
            "formatter": "verbose",
        },
        "file_error": {
            "level": "ERROR",
            "class": "config.settings.DailyRotatingFileHandler",
            "filename_pattern": os.path.join(LOG_DIR, "error_{}.log"),
            "maxBytes": 0,
            "backupCount": 0,
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "cron_debug": {
            "level": "DEBUG",
            "class": "config.settings.DailyRotatingFileHandler",
            "filename_pattern": os.path.join(LOG_DIR, "cron_debug_{}.log"),
            "maxBytes": 0,
            "backupCount": 0,
            "formatter": "verbose",
        },
        "cron_error": {
            "level": "ERROR",
            "class": "config.settings.DailyRotatingFileHandler",
            "filename_pattern": os.path.join(LOG_DIR, "cron_error_{}.log"),
            "maxBytes": 0,
            "backupCount": 0,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {  # Root logger
            "handlers": ["console", "file_debug", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["console", "file_debug", "file_error"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        # Nowy logger dla cronów
        "dashboard.management.commands": {
            "handlers": ["console", "cron_debug", "cron_error"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env("EMAIL_PORT", default=587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
