# Generated by Django 6.0 on 2026-01-05 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('start_ms', models.BigIntegerField()),
                ('end_ms', models.BigIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_trackings', to='raport.task')),
            ],
        ),
    ]
